# This is file to let you run docker image in a container instance
services:
  lightrag:
    build: .
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - rag_storage:/app/data/rag_storage
      - inputs:/app/data/inputs
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - lightrag_net
# This for devlopment purpose so that the container can access the host machine
    extra_hosts:
      - ${USE_EXTRA_HOSTS:+host.docker.internal:host-gateway}
networks:
  lightrag_net:
    driver: bridge
volumes:
  rag_storage:
  inputs:
