# This creates persistant volume to store all data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rag-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/data/rag_storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: inputs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /app/data/inputs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inputs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
